# Generated by Django 3.2.6 on 2021-08-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_producto_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='images',
            new_name='imagen',
        ),
    ]
